@hostname = http://127.0.0.1:5011/api/v1/user-roles

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10&select_fields=   HTTP/1.1

# get
###
GET {{hostname}}/2 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "title": "parent",
    "serial": "2"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 2,
    "title": "blog tags 2 upated"
}

# soft delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}

# destroy
###
POST  {{hostname}}/destroy?d=0 HTTP/1.1
content-type: application/json

{
    "id": 1
}