@hostname = http://127.0.0.1:5011/api/v1/events

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10&select_fields=   HTTP/1.1

# get
###
GET {{hostname}}/3 HTTP/1.1

# # get
# ###
# GET {{hostname}}/slug HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "title": "Tech Tonick",
    "reg_start_date": "2025-02-08",
    "reg_end_date": "2025-03-31",
    "session_start_date_time": "2025-04-03 16:30:00",
    "session_end_date_time": "2025-04-03 17:30:00",
    "place": "Canada",
    "short_description": "short description 2",
    "full_description": "long long description 2",
    "pre_requisities": "pre requisities 2",
    "terms_and_conditions": "terms and conditions 2",
    "event_type": "offline",
    "poster": "poster2.png",
    "price": 199.43,
    "discount_price": 159.67
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 1,
    "title": "Global Gardening"
}

# soft delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}

# destroy
###
POST  {{hostname}}/destroy?d=0 HTTP/1.1
content-type: application/json

{
    "id": 1
}