export const feedbackDefaultFields = [
    {
        type: 'radio-group',
        required: true,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; display: inline !important;">Overall, how entertaining was the event? (</span><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; font-style: normal; font-weight: 400; display: inline !important;">Boring&nbsp;<span style="font-weight: bold; font-style: normal; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 14px;">→</span>&nbsp;</span><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; font-style: normal; font-weight: 400; text-align: right; display: inline !important;">Fantastic)</span>',
        inline: true,
        name: 'radio-group-1742367443946-0',
        access: false,
        other: false,
        values: [
            {
                label: '1',
                value: '1',
                selected: false,
            },
            {
                label: '2',
                value: '2',
                selected: false,
            },
            {
                label: '3',
                value: '3',
                selected: false,
            },
            {
                label: '4',
                value: '4',
                selected: false,
            },
            {
                label: '5',
                value: '5',
                selected: false,
            },
            {
                label: '6',
                value: '6',
                selected: false,
            },
            {
                label: '7',
                value: '7',
                selected: false,
            },
            {
                label: '8',
                value: '8',
                selected: false,
            },
            {
                label: '9',
                value: '9',
                selected: false,
            },
            {
                label: '10',
                value: '10',
                selected: false,
            },
        ],
    },
    {
        type: 'radio-group',
        required: true,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 16px; display: inline !important;"><span style="font-style: normal; font-weight: 500; font-family: Inter, sans-serif; font-size: 16px; display: inline !important;">After the event, how inspired did you feel?</span>&nbsp;<i><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">(</span><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">Not at all</span></i></span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;</span></i><span style="font-weight: bold; font-style: normal; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 14px;">→</span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;</span><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;"><span style="font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">Completely energized!</span>)</span></i>',
        inline: true,
        name: 'radio-group-1742367840450',
        access: false,
        other: false,
        values: [
            {
                label: '1',
                value: '1',
                selected: false,
            },
            {
                label: '2',
                value: '2',
                selected: false,
            },
            {
                label: '3',
                value: '3',
                selected: false,
            },
            {
                label: '4',
                value: '4',
                selected: false,
            },
            {
                label: '5',
                value: '5',
                selected: false,
            },
            {
                label: '6',
                value: '6',
                selected: false,
            },
            {
                label: '7',
                value: '7',
                selected: false,
            },
            {
                label: '8',
                value: '8',
                selected: false,
            },
            {
                label: '9',
                value: '9',
                selected: false,
            },
            {
                label: '10',
                value: '10',
                selected: false,
            },
        ],
    },
    {
        type: 'radio-group',
        required: true,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 16px; display: inline !important;"><span style="font-family: Inter, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; display: inline !important;">Do you feel the day provided value for money?</span>&nbsp;<i><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">(</span><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">Not at all</span></i></span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;</span></i><span style="font-weight: bold; font-style: normal; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 14px;">→</span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;</span></i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; font-style: normal; font-weight: 400; text-align: right; display: inline !important;">Definitely</span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">)</span></i>',
        inline: true,
        name: 'radio-group-1742368583002',
        access: false,
        other: false,
        values: [
            {
                label: '1',
                value: '1',
                selected: false,
            },
            {
                label: '2',
                value: '2',
                selected: false,
            },
            {
                label: '3',
                value: '3',
                selected: false,
            },
            {
                label: '4',
                value: '4',
                selected: false,
            },
            {
                label: '5',
                value: '5',
                selected: false,
            },
            {
                label: '6',
                value: '6',
                selected: false,
            },
            {
                label: '7',
                value: '7',
                selected: false,
            },
            {
                label: '8',
                value: '8',
                selected: false,
            },
            {
                label: '9',
                value: '9',
                selected: false,
            },
            {
                label: '10',
                value: '10',
                selected: false,
            },
        ],
    },
    {
        type: 'radio-group',
        required: true,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; display: inline !important;">Would you recommend a similar event to a friend?</span>',
        inline: false,
        name: 'radio-group-1742368684057',
        access: false,
        other: false,
        values: [
            {
                label: 'Yes, definitely',
                value: 'Yes, definitely',
                selected: false,
            },
            {
                label: 'Maybe, if the content was changed',
                value: 'Maybe, if the content was changed',
                selected: false,
            },
            {
                label: 'Maybe, if it was cheaper',
                value: 'Maybe, if it was cheaper',
                selected: false,
            },
            {
                label: 'No, never',
                value: 'No, never',
                selected: false,
            },
        ],
    },
    {
        type: 'text',
        required: false,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; white-space-collapse: preserve; display: inline !important;">What problems did you encounter?</span>',
        className: 'form-control',
        name: 'text-1742369040018-0',
        access: false,
        subtype: 'text',
    },
    {
        type: 'radio-group',
        required: true,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 16px; display: inline !important;"><span style="font-family: Inter, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; white-space-collapse: preserve; display: inline !important;">How was the quality of the event?</span>&nbsp;<i><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">(</span><span style="font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">Not Good</span></i></span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;</span></i><span style="font-weight: bold; font-style: normal; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 14px;">→</span><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; display: inline !important;">&nbsp;Great</span></i><i><span style="color: rgb(44, 51, 69); font-family: Inter, sans-serif; font-size: 12px; text-align: right; display: inline !important;">)</span></i>',
        inline: true,
        name: 'radio-group-1742369088699',
        access: false,
        other: false,
        values: [
            {
                label: '1',
                value: '1',
                selected: false,
            },
            {
                label: '2',
                value: '2',
                selected: false,
            },
            {
                label: '3',
                value: '3',
                selected: false,
            },
            {
                label: '4',
                value: '4',
                selected: false,
            },
            {
                label: '5',
                value: '5',
                selected: false,
            },
            {
                label: '6',
                value: '6',
                selected: false,
            },
            {
                label: '7',
                value: '7',
                selected: false,
            },
            {
                label: '8',
                value: '8',
                selected: false,
            },
            {
                label: '9',
                value: '9',
                selected: false,
            },
            {
                label: '10',
                value: '10',
                selected: false,
            },
        ],
    },
    {
        type: 'text',
        required: false,
        label: '<span style="color: rgb(44, 51, 69); font-family: Inter, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, sans-serif; font-size: 16px; font-style: normal; font-weight: 500; white-space-collapse: preserve; display: inline !important;">Any suggestions for future event topics?</span>',
        className: 'form-control',
        name: 'text-1742369211234',
        access: false,
        subtype: 'text',
    },
    {
        type: "textarea",
        required: false,
        label: "<span style=\"color: rgb(44, 51, 69); font-size: 14px; font-style: normal; font-weight: 400; display: inline !important;\">Any final comments?</span>",
        className: "form-control",
        name: "textarea-1742459231910-0",
        access: false,
        subtype: "textarea",
        rows: 3
      },
];
